<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2201" started-at="2018-01-27T20:05:34Z" finished-at="2018-01-27T20:05:36Z">
    <groups>
      <group name="google">
        <method signature="GoogleApiTest.googleApiTest()[pri:0, instance:com.fluentWait.test.GoogleApiTest@6a4f787b]" name="googleApiTest" class="com.fluentWait.test.GoogleApiTest"/>
      </group> <!-- google -->
      <group name="demo">
        <method signature="GoogleApiTest.googleApiTest()[pri:0, instance:com.fluentWait.test.GoogleApiTest@6a4f787b]" name="googleApiTest" class="com.fluentWait.test.GoogleApiTest"/>
      </group> <!-- demo -->
    </groups>
    <test name="Default test" duration-ms="2201" started-at="2018-01-27T20:05:34Z" finished-at="2018-01-27T20:05:36Z">
      <class name="com.fluentWait.test.GoogleApiTest">
        <test-method status="FAIL" signature="googleApiTest()[pri:0, instance:com.fluentWait.test.GoogleApiTest@6a4f787b]" name="googleApiTest" duration-ms="2153" started-at="2018-01-28T01:35:34Z" finished-at="2018-01-28T01:35:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:652)at org.testng.Assert.assertEquals(Assert.java:662)at com.fluentWait.framework.RestAssuredConfiguration.getResponse(RestAssuredConfiguration.java:32)at com.fluentWait.test.GoogleApiTest.googleApiTest(GoogleApiTest.java:29)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleApiTest -->
      </class> <!-- com.fluentWait.test.GoogleApiTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
